#!/usr/bin/env bash
#
# Builds every distributable artifact from a clean tag, into an empty versioned directory, and
# writes a manifest that says exactly what was built and from what.
#
# The point is not convenience. A release built by hand is a release nobody can reproduce: the
# version in the binary comes from whatever was last typed into export_presets.cfg, the engine is
# whatever `godot` happens to resolve to today, the output lands beside the previous build so
# stale files ship with it, and nothing records which commit any of it came from. Every one of
# those is silent, and every one of them is only discovered by somebody holding the wrong build.
#
#     tools/release.sh v0.3.0        # build that tag
#     tools/release.sh --relock      # re-record the engine, template and SDK hashes
#
# What it refuses to do, and why each refusal is worth having:
#
#   - Build from a dirty tree. The manifest names a commit; if the tree has uncommitted changes
#     that commit does not describe what shipped.
#   - Build from a tag that does not exist, or a commit that is not that tag. A version number
#     that is not anchored to a tag is a version number that can be reused.
#   - Build with an engine or export templates that differ from the pinned ones. The engine is
#     part of the artifact — a Godot patch release changes the binary — so an unpinned engine
#     makes "reproducible" untrue in the one way nobody checks.
#   - Sign nothing while claiming to. See the signing section: without credentials it says so and
#     marks the artifacts unsigned rather than shipping them as if they were not.
#
# Everything it writes goes under build/<version>/, which must not already exist.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

LOCK_FILE="tools/engine.lock"
TEMPLATE_DIR="${GODOT_TEMPLATE_DIR:-$HOME/Library/Application Support/Godot/export_templates}"
GODOT="${GODOT:-godot}"
WAVEDASH_ADDON_DIR="addons/wavedash"

# The vendored Wavedash SDK files, as copied from upstream. The .uid files are tracked but not
# hashed: Godot regenerates them, so pinning them would fail on churn that changes no behaviour.
WAVEDASH_SDK_FILES=(
  "LICENSE"
  "plugin.cfg"
  "README.md"
  "WavedashConstants.gd"
  "WavedashPlugin.gd"
  "WavedashSDK.gd"
)

# The presets, and the file each one produces. Names must match export_presets.cfg exactly —
# `--export-release` takes the preset's name and fails loudly on a typo, which is the behaviour
# wanted here.
PRESETS=("macOS" "Windows" "Linux" "Web")
OUTPUTS=("robo_rush.zip" "robo_rush.exe" "robo_rush.x86_64" "index.html")

# The release templates each preset consumes. Hashed and pinned, because they are as much a part
# of the artifact as the project's own source is.
TEMPLATES=(
  "macos.zip"
  "windows_release_x86_64.exe"
  "linux_release.x86_64"
  "web_nothreads_release.zip"
)

die() { printf '\nrelease: %s\n' "$1" >&2; exit 1; }
note() { printf '  %s\n' "$1"; }

sha256() { shasum -a 256 "$1" | cut -d' ' -f1; }


# --- Engine and template pinning ---------------------------------------------------

engine_version() {
  "$GODOT" --version 2>/dev/null | head -1 | tr -d '\n'
}

## The add-on's own declared version, from the manifest Godot reads.
wavedash_sdk_version() {
  grep '^version=' "$WAVEDASH_ADDON_DIR/plugin.cfg" | cut -d= -f2- | tr -d '"'
}

## The Wavedash CLI that uploads builds. Recorded rather than enforced here — this script never
## uploads — so CI has an approved version to compare against before it hands over a token.
wavedash_cli_version() {
  command -v wavedash >/dev/null 2>&1 || return 0
  wavedash --version 2>/dev/null | head -1 | tr -d '\n'
}

## Writes the lock file from whatever is installed now. Run deliberately, when the engine is
## upgraded on purpose, so that an upgrade is a reviewable diff rather than a silent change in
## what the next release is built with.
relock() {
  local version templates_version sdk_version sdk_commit cli_version
  version="$(engine_version)"
  templates_version="$(cat "$TEMPLATE_DIR"/*/version.txt 2>/dev/null | head -1)"
  [ -n "$version" ] || die "could not run '$GODOT --version'"

  sdk_version="$(wavedash_sdk_version)"
  [ -n "$sdk_version" ] || die "no version= in $WAVEDASH_ADDON_DIR/plugin.cfg"
  cli_version="$(wavedash_cli_version)"

  # Upstream publishes no tags, so the commit the vendored tree came from exists nowhere in the
  # files themselves. It has to be carried across a relock, or supplied when the SDK is upgraded.
  sdk_commit="${WAVEDASH_SDK_COMMIT:-$(grep '^wavedash_sdk_commit=' "$LOCK_FILE" 2>/dev/null | cut -d= -f2-)}"
  [ -n "$sdk_commit" ] || die \
    "no wavedash_sdk_commit in $LOCK_FILE. Re-run with: WAVEDASH_SDK_COMMIT=<sha> tools/release.sh --relock"

  {
    echo "# Generated by tools/release.sh --relock. Do not edit by hand."
    echo "# The engine and export templates a release is built with are part of the artifact:"
    echo "# a Godot patch release changes the binary, so an unpinned engine makes a build"
    echo "# reproducible only by accident."
    echo "engine_version=$version"
    echo "templates_version=$templates_version"
    for template in "${TEMPLATES[@]}"; do
      local path="$TEMPLATE_DIR/$templates_version/$template"
      [ -f "$path" ] || die "export template missing: $path"
      echo "template.$template=$(sha256 "$path")"
    done
    echo
    echo "# The vendored Wavedash SDK ships inside the web build, so it is part of the artifact"
    echo "# too. Upstream has no tags: the commit is the only durable name for what was copied."
    echo "wavedash_sdk_version=$sdk_version"
    echo "wavedash_sdk_commit=$sdk_commit"
    for file in "${WAVEDASH_SDK_FILES[@]}"; do
      local addon_path="$WAVEDASH_ADDON_DIR/$file"
      [ -f "$addon_path" ] || die "Wavedash SDK file missing: $addon_path"
      echo "wavedash_sdk.$file=$(sha256 "$addon_path")"
    done
    if [ -n "$cli_version" ]; then
      echo "wavedash_cli_version=$cli_version"
    fi
  } > "$LOCK_FILE"

  echo "Wrote $LOCK_FILE:"
  sed 's/^/  /' "$LOCK_FILE"
}

## Fails unless the installed engine and templates are byte-for-byte the pinned ones.
verify_engine() {
  [ -f "$LOCK_FILE" ] || die "$LOCK_FILE is missing. Run: tools/release.sh --relock"

  local pinned_engine pinned_templates actual
  pinned_engine="$(grep '^engine_version=' "$LOCK_FILE" | cut -d= -f2-)"
  pinned_templates="$(grep '^templates_version=' "$LOCK_FILE" | cut -d= -f2-)"
  actual="$(engine_version)"

  [ "$actual" = "$pinned_engine" ] || die \
    "engine is '$actual', pinned is '$pinned_engine'. Upgrade deliberately: tools/release.sh --relock"
  note "engine $actual"

  for template in "${TEMPLATES[@]}"; do
    local path="$TEMPLATE_DIR/$pinned_templates/$template"
    [ -f "$path" ] || die "export template missing: $path (see export_presets.cfg for how to install)"
    local expected got
    expected="$(grep "^template\.$template=" "$LOCK_FILE" | cut -d= -f2-)"
    got="$(sha256 "$path")"
    [ "$expected" = "$got" ] || die "export template $template does not match the pinned hash"
  done
  note "export templates $pinned_templates verified (${#TEMPLATES[@]} hashes)"

  verify_wavedash_sdk
}

## Fails unless the vendored SDK is byte-for-byte the pinned one. Vendoring already keeps the
## add-on out of the AssetStore's reach, so this catches the other way it drifts: an in-tree edit
## nobody meant to ship, or a copy-in that skipped the lock file.
verify_wavedash_sdk() {
  local pinned_version actual_version
  pinned_version="$(grep '^wavedash_sdk_version=' "$LOCK_FILE" | cut -d= -f2-)"
  [ -n "$pinned_version" ] || die \
    "no wavedash_sdk_version in $LOCK_FILE. Run: tools/release.sh --relock"
  actual_version="$(wavedash_sdk_version)"

  [ "$actual_version" = "$pinned_version" ] || die \
    "Wavedash SDK is '$actual_version', pinned is '$pinned_version'. Upgrade deliberately: WAVEDASH_SDK_COMMIT=<sha> tools/release.sh --relock"

  for file in "${WAVEDASH_SDK_FILES[@]}"; do
    local addon_path="$WAVEDASH_ADDON_DIR/$file"
    [ -f "$addon_path" ] || die "Wavedash SDK file missing: $addon_path"
    local expected got
    expected="$(grep "^wavedash_sdk\.$file=" "$LOCK_FILE" | cut -d= -f2-)"
    got="$(sha256 "$addon_path")"
    [ "$expected" = "$got" ] || die "Wavedash SDK file $file does not match the pinned hash"
  done
  note "Wavedash SDK $pinned_version verified (${#WAVEDASH_SDK_FILES[@]} hashes)"
}


# --- Version, from the tag ----------------------------------------------------------

## Rewrites the version fields in export_presets.cfg from the tag, so the number inside the binary
## and the number on the release are the same by construction rather than by somebody remembering.
## Restored afterwards by the trap in main, because the working file is not the release artifact.
apply_version() {
  local semver="$1"
  local windows_version="${semver}.0"

  # macOS wants a dotted version; Windows wants four components. Both presets are rewritten in
  # place, and both are put back before this script exits.
  perl -pi -e "s|^application/short_version=.*|application/short_version=\"$semver\"|" export_presets.cfg
  perl -pi -e "s|^application/version=.*|application/version=\"$semver\"|" export_presets.cfg
  perl -pi -e "s|^application/product_version=.*|application/product_version=\"$windows_version\"|" export_presets.cfg
  perl -pi -e "s|^application/file_version=.*|application/file_version=\"$windows_version\"|" export_presets.cfg
  note "version $semver written into the export presets"
}


# --- Signing ------------------------------------------------------------------------

## macOS signing and notarisation, when there are credentials to do it with.
##
## Deliberately not silent when there are none. An unsigned macOS build is not a broken build, it
## is a build Gatekeeper refuses to open without the user right-clicking — which is a fine state
## for a test build and a bad surprise for a public one. The manifest records which it is, so the
## difference is visible to whoever publishes rather than to whoever downloads.
sign_macos() {
  local artifact="$1"
  if [ -z "${MACOS_SIGNING_IDENTITY:-}" ]; then
    note "macOS: unsigned (set MACOS_SIGNING_IDENTITY to a Developer ID to sign)"
    echo "unsigned"
    return
  fi

  codesign --force --timestamp --options runtime \
    --sign "$MACOS_SIGNING_IDENTITY" "$artifact" >/dev/null 2>&1 \
    || die "codesign failed for $artifact"

  if [ -z "${MACOS_NOTARY_PROFILE:-}" ]; then
    note "macOS: signed, not notarised (set MACOS_NOTARY_PROFILE for notarytool)"
    echo "signed"
    return
  fi

  xcrun notarytool submit "$artifact" --keychain-profile "$MACOS_NOTARY_PROFILE" --wait \
    || die "notarisation failed for $artifact"
  xcrun stapler staple "$artifact" || die "stapling failed for $artifact"
  note "macOS: signed and notarised"
  echo "notarised"
}

sign_windows() {
  local artifact="$1"
  if [ -z "${WINDOWS_SIGNING_PFX:-}" ]; then
    note "Windows: unsigned (set WINDOWS_SIGNING_PFX and WINDOWS_SIGNING_PASSWORD to sign)"
    echo "unsigned"
    return
  fi
  command -v osslsigncode >/dev/null || die "osslsigncode is needed to sign Windows artifacts"
  osslsigncode sign -pkcs12 "$WINDOWS_SIGNING_PFX" -pass "${WINDOWS_SIGNING_PASSWORD:-}" \
    -t http://timestamp.digicert.com -in "$artifact" -out "$artifact.signed" >/dev/null \
    || die "osslsigncode failed for $artifact"
  mv "$artifact.signed" "$artifact"
  echo "signed"
}


# --- Main ---------------------------------------------------------------------------

main() {
  if [ "${1:-}" = "--relock" ]; then
    relock
    return
  fi

  local tag="${1:-}"
  [ -n "$tag" ] || die "usage: tools/release.sh <tag>   (or --relock)"

  echo "Robo Rush release $tag"

  # A clean tree, or the commit in the manifest is a lie about what was built.
  [ -z "$(git status --porcelain)" ] || die "the working tree is dirty; commit or stash first"
  git rev-parse -q --verify "refs/tags/$tag" >/dev/null || die "tag '$tag' does not exist"
  [ "$(git rev-parse "$tag^{commit}")" = "$(git rev-parse HEAD)" ] \
    || die "HEAD is not tag '$tag'; check it out first"

  local commit semver output
  commit="$(git rev-parse HEAD)"
  semver="${tag#v}"
  output="build/$semver"

  # Empty and versioned. Building into a directory that already has files in it is how a stale
  # artifact from a previous version ends up inside a release.
  [ ! -e "$output" ] || die "$output already exists; remove it or pick another tag"

  verify_engine

  # The suite is part of the release gate: an artifact nobody has tested is not a release
  # candidate, it is a build.
  note "running the test suite"
  "$GODOT" --headless --fixed-fps 60 res://tests/test_runner.tscn >/dev/null 2>&1 \
    || die "the test suite failed; nothing was built"

  # The presets are edited in place and put back however this exits, including on failure. The
  # working file is not the artifact, and a release that left a rewritten version behind would
  # make the next developer's diff start with a change they did not make.
  trap 'git checkout -- export_presets.cfg 2>/dev/null || true' EXIT
  apply_version "$semver"

  mkdir -p "$output"
  local manifest="$output/manifest.json"
  echo "{" > "$manifest"
  echo "  \"version\": \"$semver\"," >> "$manifest"
  echo "  \"tag\": \"$tag\"," >> "$manifest"
  echo "  \"commit\": \"$commit\"," >> "$manifest"
  echo "  \"engine\": \"$(engine_version)\"," >> "$manifest"
  echo "  \"built\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"," >> "$manifest"
  echo "  \"artifacts\": [" >> "$manifest"

  local index=0
  for preset in "${PRESETS[@]}"; do
    local lower
    lower="$(printf '%s' "$preset" | tr '[:upper:]' '[:lower:]')"
    local target_dir="$output/$lower"
    mkdir -p "$target_dir"
    local artifact="$target_dir/${OUTPUTS[$index]}"

    note "exporting $preset"
    "$GODOT" --headless --export-release "$preset" "$artifact" >/dev/null 2>&1 \
      || die "export failed for $preset"
    [ -f "$artifact" ] || die "$preset reported success but produced no file"

    local signing="not applicable"
    case "$preset" in
      macOS) signing="$(sign_macos "$artifact" | tail -1)" ;;
      Windows) signing="$(sign_windows "$artifact" | tail -1)" ;;
    esac

    # Size is the whole target directory for Web, which is many files, and the single artifact
    # otherwise. Both are what somebody downloading it actually receives.
    local size
    size="$(du -sk "$target_dir" | cut -f1)"

    [ $index -eq 0 ] || echo "    }," >> "$manifest"
    {
      echo "    {"
      echo "      \"target\": \"$preset\","
      echo "      \"path\": \"$lower/${OUTPUTS[$index]}\","
      echo "      \"sha256\": \"$(sha256 "$artifact")\","
      echo "      \"kilobytes\": $size,"
      echo "      \"signing\": \"$signing\""
    } >> "$manifest"

    index=$((index + 1))
  done

  echo "    }" >> "$manifest"
  echo "  ]" >> "$manifest"
  echo "}" >> "$manifest"

  # A flat checksum file as well as the manifest, because that is what a download page publishes
  # and what `shasum -c` consumes.
  (cd "$output" && find . -type f ! -name SHA256SUMS ! -name manifest.json -exec shasum -a 256 {} + > SHA256SUMS)

  echo
  echo "Built $tag into $output"
  sed 's/^/  /' "$manifest"
}

main "$@"
